name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]

env:
#   AWS_S3_BUCKET : "uk-demo-bucket"
    AWS_REGION : "us-west-2"
  
permissions:
      id-token: write
      contents: read 

jobs:
 job_1:  
    name: build
    runs-on: windows-2019

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Install AWS CLI
      run: choco install awscli
   
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Create a temporary artifact downloads folder
      run: mkdir ${{ github.workspace }}\build

    - name: Build solution
      run: msbuild DemoWebApplication/DemoWebApplication.sln /p:UseSharedCompilation=false /t:rebuild /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True  /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl=${{ github.workspace }}\build

    - name: Move the AppSpec file to build folder
      run: |
           Move-Item -Path ${{ github.workspace }}\build-spec\DemoWebApplication\after-install.ps1 -Destination ${{ github.workspace }}\build\after-install.ps1 
           Move-Item -Path ${{ github.workspace }}\build-spec\DemoWebApplication\before-install.ps1 -Destination ${{ github.workspace }}\build\before-install.ps1
           Move-Item -Path ${{ github.workspace }}\build-spec\DemoWebApplication\appspec.yml -Destination ${{ github.workspace }}\build\appspec.yml  
        
    - name: Zip the Artifacts
      run: Compress-Archive -Path ${{ github.workspace }}\build\* -Destination ${{ github.workspace }}\build.zip
    
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
          role-to-assume: ${{ secrets.EC2_CODEDEPLOY_ARN }}
          role-session-name: Github-S3-Upload
          aws-region: ${{ env.AWS_REGION }}  

    # env:
    #     AWS_S3_BUCKET: ${{ env.AWS_S3_BUCKET }}

    - name: Pushing a revision to AWS S3
      run: | 
          aws deploy push --application-name CodeDeploy --description "Testing the DemoWebApplication" --ignore-hidden-files --s3-location s3://${{ secrets.AWS_S3_BUCKET }}/demobuild.zip --source ${{ github.workspace }}\build

    - name: Create CodeDeploy Deployment
      id: deploy
      run: |
          aws deploy create-deployment --application-name CodeDeploy --deployment-group-name CodeDeployGroup --deployment-config-name CodeDeployDefault.OneAtATime --s3-location bucket=${{ secrets.AWS_S3_BUCKET }},bundleType=zip,key=loginbuild.zip